# Generated by Django 2.1.7 on 2019-03-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playground', '0002_delete_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=20)),
                ('enddate', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
