# Generated by Django 2.1.7 on 2019-08-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_auto_20190801_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('major', models.CharField(max_length=32)),
                ('gpa', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
