# Generated by Django 2.2.4 on 2019-08-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20190802_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default='B.S', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default='Software Developer', max_length=32),
            preserve_default=False,
        ),
    ]
