# Generated by Django 2.2.4 on 2019-08-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20190802_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default='Software Developer', max_length=32),
            preserve_default=False,
        ),
    ]
