# Generated by Django 2.2.4 on 2019-08-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_experience_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default='B.S.', max_length=8),
            preserve_default=False,
        ),
    ]
